# Run tests and deploy to https://walles.github.io/ttt.

name: test-and-deploy
on: [push]
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      - run: dart format --output=none --set-exit-if-changed lib/ test/
      - run: flutter analyze
      - run: flutter test

      # Deploy new main commits to Github pages
      - uses: bluefireteam/flutter-gh-pages@v7
        if: github.ref == 'refs/heads/main'
        with:
          # Sends the deploy to walles/ttt rather than just walles
          baseHref: /ttt/
